services:
  server-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-server
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/server/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000

  ui-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-ui
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/ui/node_modules
    environment:
      - NODE_ENV=development

  nginx-dev:
    profiles: ["dev"]
    image: nginx:1.27-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ui-dev
      - server-dev
